# Generated by Django 5.2.4 on 2025-08-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
