# Generated by Django 5.2.4 on 2025-08-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_payment_method_donation_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='bank_transfer_proof',
            field=models.FileField(blank=True, null=True, upload_to='bank_proofs/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='ecocash_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('ecocash', 'EcoCash'), ('bank', 'Bank Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
