# Generated by Django 5.2.4 on 2025-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation_ecocash_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='donation_proofs/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
