# Generated by Django 5.2.4 on 2025-08-06 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost_contactmessage_event_project_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Entrepreneurship', 'Entrepreneurship'), ('Community Development', 'Community Development'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Other', 'Other')], default='Education', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Shoko', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
