# Generated by Django 5.2.4 on 2025-08-06 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_duration_project_duration_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('user', 'project')},
        ),
    ]
