# Generated by Django 5.2.4 on 2025-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectapplication_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='application_images/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.projectapplication')),
            ],
        ),
    ]
