# Generated by Django 5.2.4 on 2025-08-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tasknotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
