# Generated by Django 5.2.4 on 2025-08-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tasknotification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.project'),
        ),
    ]
