# Generated by Django 5.2.4 on 2025-08-07 20:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
