# Generated by Django 5.2.4 on 2025-08-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_donation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('podcast', 'Podcast'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('talk', 'Talk Show'), ('watch_party', 'Watch Party'), ('class', 'Live Class'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('live', 'Live'), ('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='media/donation_proofs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects/'),
        ),
    ]
