# Generated by Django 5.2.4 on 2025-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_category_event_event_image_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the event (YouTube, Zoom, etc.)', null=True),
        ),
    ]
