# Generated by Django 5.2.4 on 2025-08-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Counseling Site Setting',
                'verbose_name_plural': 'Counseling Site Settings',
            },
        ),
    ]
